#!/usr/bin/env bash
# deploy.sh — Train on Kaggle, upload to GitHub Releases, push code.
# Usage: bash deploy.sh
set -euo pipefail

REPO_GH="shubhamtiwari1602/da6401-assignment2"
KERNEL="shubhamtiwari16/assign2-train"
RELEASE_TAG="v1.0"
CKPT_DIR="./checkpoints"

# ── Preflight ──────────────────────────────────────────────────────────────
echo "[1/5] Checking tools..."
command -v kaggle >/dev/null 2>&1 || { echo "ERROR: kaggle CLI not found. Run: pipx install kaggle"; exit 1; }
command -v gh     >/dev/null 2>&1 || { echo "ERROR: gh not found. Run: brew install gh && gh auth login"; exit 1; }
gh auth status >/dev/null 2>&1    || { echo "ERROR: gh not authenticated. Run: gh auth login"; exit 1; }

# ── Push Kaggle kernel ─────────────────────────────────────────────────────
echo "[2/5] Pushing Kaggle kernel..."
kaggle kernels push -p ./kaggle_kernel/
echo "      Kernel pushed: $KERNEL"

# ── Wait for kernel to complete ────────────────────────────────────────────
echo "[3/5] Waiting for training to finish (this takes ~2 hours on GPU)..."
echo "      Polling every 60 seconds..."
SECONDS_WAITED=0
while true; do
  RAW=$(kaggle kernels status "$KERNEL" 2>&1 || true)
  # Extract status keyword from output
  STATUS=$(echo "$RAW" | grep -oiE 'running|complete|error|queued|cancelAcknowledged' | head -1 | tr '[:upper:]' '[:lower:]' || echo "unknown")
  MINS=$(( SECONDS_WAITED / 60 ))
  echo "  [+${MINS}m] status: $STATUS"
  [[ "$STATUS" == "complete" ]] && break
  [[ "$STATUS" == "error" || "$STATUS" == "cancelacknowledged" ]] && {
    echo "ERROR: Kaggle kernel failed or was cancelled."
    echo "Full status output: $RAW"
    exit 1
  }
  sleep 60
  SECONDS_WAITED=$(( SECONDS_WAITED + 60 ))
done
echo "      Training complete!"

# ── Download outputs ───────────────────────────────────────────────────────
echo "[4/5] Downloading checkpoints from Kaggle..."
mkdir -p "$CKPT_DIR"
kaggle kernels output "$KERNEL" -p "$CKPT_DIR/"

echo "      Checkpoint sizes:"
for name in classifier.pth localizer.pth unet.pth; do
  if [[ -f "$CKPT_DIR/$name" ]]; then
    size=$(python3 -c "import os; print(f'{os.path.getsize(\"$CKPT_DIR/$name\")/1e6:.1f}')")
    echo "        $name: ${size} MB"
  else
    echo "        $name: MISSING — check Kaggle kernel output"
    exit 1
  fi
done

# ── Create GitHub Release ──────────────────────────────────────────────────
echo "[5/5] Publishing GitHub Release $RELEASE_TAG..."
gh release delete "$RELEASE_TAG" --repo "$REPO_GH" --yes 2>/dev/null || true
gh release create "$RELEASE_TAG" \
  --repo "$REPO_GH" \
  --title "Trained checkpoints (GAP architecture)" \
  --notes "Auto-generated by deploy.sh. Contains classifier.pth, localizer.pth, unet.pth." \
  "$CKPT_DIR/classifier.pth" \
  "$CKPT_DIR/localizer.pth" \
  "$CKPT_DIR/unet.pth"
echo "      Release published."

# ── Push code ─────────────────────────────────────────────────────────────
echo "[6/6] Committing and pushing updated code..."
git add multitask.py kaggle_kernel/ deploy.sh
git diff --cached --quiet && echo "      (no code changes to commit)" || \
  git commit -m "fix: download checkpoints from GitHub Releases at runtime"
git push

echo ""
echo "======================================================"
echo " Done! Now resubmit on Gradescope."
echo " The autograder will download the checkpoints from:"
echo " https://github.com/$REPO_GH/releases/download/$RELEASE_TAG/"
echo "======================================================"
